### ISSUE TITLE
What is this error: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by gaohongxiang** [zkparty/trusted-setup-frontend#155]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/33713367/215004275-910cd3e8-793c-4a09-b1d9-74259085f9d7.png">

**Comment by NicoSerranoP** [comment]
Hi! It looks like there was a network error when you were pinging the sequencer. Could you check if you get any info with a GET request to [https://seq.ceremony.ethereum.org/info/status](url) ? (Just open the link in the browser and it should show you something like `{"lobby_size":1877,"num_contributions":22760,"sequencer_address":"0xfAA3A87713253D44E33C994556f7727AC71937f0"}` ).

If that is the case, please try again, the internet connection might have dropped. If you get the error again, could you open the error log and send me a screenshot of it? In our development phase, we were having problems with the uploaded json size. Right now it is fixed but I want to double check

**Comment by gaohongxiang** [comment]
The get request can get the information. Tried many times. Still getting an error.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/33713367/215312886-f7facdee-0875-4b18-9c5d-4a6cb3374a54.png">
Another problem is that the number of people in the lobby barely changes or even increases after hours of queuing. I wonder if this number refers to where I am currently at? Is it my turn when the number turns to 0?

**Comment by cuikunshuo** [comment]
I don't think you can succeed when the number becomes "0", which seems to indicate how many people are currently in line.

**Comment by gaohongxiang** [comment]
I have been waiting on this page for some days now. I don't know when I will be able to enter the ceremony. It always shows at 3% chance of contributing in the next hour. How is this percentage generated? If it is based on luck, is it not fair to those who come in first?

**Comment by glamperd** [comment]
@gaohongxiang Yes, you will be selected by random chance. It is not fairto those such as you, who end up waiting longer than you expect. However, this approach keeps the API much simpler and more secure, and security is very important to the success of the ceremony. We are still in the early days of the open contribution phase. With 42 days remaining, you should still have plenty of opportunity to contribute. Come back at a quieter time if you wish. Thanks for your interest.

**Comment by NicoSerranoP** [comment]
@gaohongxiang the pinging to the sequencer after an error message should continue automatically. Is that the case or are you stuck right after the ERR_CONNECTION_RESET?

**Comment by gaohongxiang** [comment]
Now working fine, thanks
